Refactor VoiceCommandManager for taskmaster
smartdevicelink/sdl_java_suite pull request #1553
Opened 2020-11-06 19:45 UTC by RHenigan

Fixes #1549 

This PR is **[not ready]** for review.

### Risk
This PR makes **[minor]** API changes.

### Testing Plan
- [ ] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [ ] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).
- [ ] I have tested Android, Java SE, and Java EE

#### Unit Tests
Updated VoiceCommandManagerTests to accound for taskmaster dependancy

### Summary
This PR will create `VoiceCommandReplaceOperation` which will use send the list of `DeleteCommand` and `AddCommand` RPCs. `BaseVoiceCommandManager` has been refactored to use taskMaster Queues.

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2020-11-09 14:14 UTC, RHenigan commented
![](https://github.trello.services/images/mini-trello-icon.png) [(5) Refactor `VoiceCommandManager` to use queues [1]](https://trello.com/c/jyGUBXpC/1562-5-refactor-voicecommandmanager-to-use-queues-1)

2020-11-18 16:13 UTC, bilal-alsharifi requested changes

2020-11-18 17:56 UTC, RHenigan commented on base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseVoiceCommandManager.java
> +                DebugTool.logError(TAG, "The failed Add and Delete Commands: " + errorObject);
Updated to only print when errorObject is not empty

2020-11-18 17:56 UTC, RHenigan commented on base/src/main/java/com/smartdevicelink/managers/screen/menu/VoiceCommandUpdateOperation.java
> +public class VoiceCommandUpdateOperation extends Task {
fixed

2020-11-18 17:56 UTC, RHenigan commented on base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseVoiceCommandManager.java
> +        transactionQueue.close();
added null check

2020-11-18 17:57 UTC, RHenigan commented on base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseVoiceCommandManager.java
>      public void setVoiceCommands(List<VoiceCommand> voiceCommands) {
Updated to allow for an emptylist to be set, added unit test for the updateOperation

2020-11-18 20:06 UTC, RHenigan commented on base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseVoiceCommandManager.java
>          waitingOnHMIUpdate = false;
removed old HMI Status logic

2020-11-18 20:07 UTC, RHenigan commented on base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseVoiceCommandManager.java
>      boolean waitingOnHMIUpdate;
removed old HMI Status Logic

2020-11-19 19:23 UTC, bilal-alsharifi requested changes

2020-11-19 21:47 UTC, RHenigan commented on base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseVoiceCommandManager.java
>      public void setVoiceCommands(List<VoiceCommand> voiceCommands) {
added a check

2020-11-19 21:47 UTC, RHenigan commented on base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseVoiceCommandManager.java
>          lastVoiceCommandId = voiceCommandIdMin;
removed this assignment

2020-11-19 21:47 UTC, RHenigan commented on base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseVoiceCommandManager.java
> +        this.currentVoiceCommands = new ArrayList<>();
removed this to align with iOS code

2020-11-19 21:48 UTC, RHenigan commented on base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseVoiceCommandManager.java
>      private void update() {
removed update method and added to set voice commands

2020-11-19 21:48 UTC, RHenigan commented on base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseVoiceCommandManager.java
>          }
changed to null check

2020-11-19 21:49 UTC, RHenigan commented on base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseVoiceCommandManager.java
> +            updateOperation = null;
removed assignment in the transactionQueue check

2020-11-19 21:49 UTC, RHenigan commented on base/src/main/java/com/smartdevicelink/managers/screen/menu/VoiceCommandUpdateOperation.java
> +        this.currentVoiceCommands = oldVoiceCommands;
changed to copy oldVoiceCommands into currentVoiceCommands

2020-11-19 21:52 UTC, RHenigan commented on base/src/main/java/com/smartdevicelink/managers/screen/menu/VoiceCommandUpdateOperation.java
> +                        voiceCommandListener.updateVoiceCommands(currentVoiceCommands, errorObject);
added null check for listener

2020-11-19 21:52 UTC, RHenigan commented on base/src/main/java/com/smartdevicelink/managers/screen/menu/VoiceCommandUpdateOperation.java
> +                if (!deleteResponse.getSuccess()) {
updated

2020-11-19 21:53 UTC, RHenigan commented on base/src/main/java/com/smartdevicelink/managers/screen/menu/VoiceCommandUpdateOperation.java
> +                            errorObject.put(deleteCommand, response.getInfo());
change no longer needed due to change in the onResponse methods

2020-11-19 21:53 UTC, RHenigan commented on base/src/main/java/com/smartdevicelink/managers/screen/menu/VoiceCommandUpdateOperation.java
> +            if (correlationId == deleteCommand.getCorrelationID()) {
Updated

2020-11-19 21:54 UTC, RHenigan commented on base/src/main/java/com/smartdevicelink/managers/screen/menu/VoiceCommandUpdateOperation.java
> +                    removeCurrentVoiceCommandWithCorrelationId(correlationId);
Changed as suggested, new method names are `removeCurrentVoiceCommandForCorrelatingDeleteCommand` and `pendingVoiceCommandForCorrelatingAddCommand`

2020-11-19 21:54 UTC, RHenigan commented on base/src/main/java/com/smartdevicelink/managers/screen/menu/VoiceCommandUpdateOperation.java
> +                if (!addResponse.getSuccess()) {
updated

2020-11-19 21:55 UTC, RHenigan commented on base/src/main/java/com/smartdevicelink/managers/screen/menu/VoiceCommandUpdateOperation.java
> +                            errorObject.put(addCommand, response.getInfo());
change no longer needed with changes to onResponse method

2020-11-19 21:57 UTC, RHenigan commented on base/src/main/java/com/smartdevicelink/managers/screen/menu/VoiceCommandUpdateOperation.java
> +                            onError();
Changed to `onFinished()` as this is how it was implemented for other tasks such as `SoftButtonReplaceOperation` and `TextAndGraphicUpdateOperation`

2020-11-20 15:36 UTC, RHenigan commented on base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseVoiceCommandManager.java
> +        if (voiceCommands == null || voiceCommands.equals(this.voiceCommands)) {
Implemented Methods in `VoiceCommand`

2020-11-20 15:36 UTC, RHenigan commented on base/src/main/java/com/smartdevicelink/managers/screen/menu/BaseVoiceCommandManager.java
> +            DebugTool.logInfo(TAG, "Voice commands list was null, returning");
updated log message

2020-11-20 15:37 UTC, RHenigan commented on base/src/main/java/com/smartdevicelink/managers/screen/menu/VoiceCommandUpdateOperation.java
> +                        }
implemented

2020-11-20 15:38 UTC, RHenigan commented on base/src/main/java/com/smartdevicelink/managers/screen/menu/VoiceCommandUpdateOperation.java
> +                        foundDeleteCommand = deleteCommand;
implemented

2020-11-20 15:38 UTC, RHenigan commented on base/src/main/java/com/smartdevicelink/managers/screen/menu/VoiceCommandUpdateOperation.java
> +                        foundAddCommand = addCommand;
implemented

2020-11-20 16:14 UTC, bilal-alsharifi commented on android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/menu/VoiceCommandManagerTests.java
There is an unused import in this class

2020-11-20 16:17 UTC, RHenigan commented on android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/menu/VoiceCommandManagerTests.java
updated

2020-11-20 16:18 UTC, RHenigan commented on base/src/main/java/com/smartdevicelink/managers/screen/menu/VoiceCommand.java
> +        result += ((getCommandId() == 0) ? 0 : Integer.rotateLeft(getCommandId(), 1));
updated

2020-11-20 16:18 UTC, RHenigan commented on base/src/main/java/com/smartdevicelink/managers/screen/menu/VoiceCommand.java
> +        result += ((getVoiceCommandSelectionListener() == null) ? 0 : Integer.rotateLeft(getVoiceCommandSelectionListener().hashCode(), 2));
updated

2020-11-20 16:18 UTC, RHenigan commented on base/src/main/java/com/smartdevicelink/managers/screen/menu/VoiceCommand.java
> +import com.smartdevicelink.managers.screen.SoftButtonObject;
updated

2020-11-20 20:28 UTC, bilal-alsharifi approved these changes

2020-12-09 17:50 UTC, merged