Add SeekStreamingIndicator changes
smartdevicelink/sdl_java_suite pull request #1562
Opened 2020-11-17 19:22 UTC by RHenigan

Fixes #[871]

This PR is **[not ready]** for review.

### Risk
This PR makes **[no / minor / major]** API changes.

### Testing Plan
- [ ] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [ ] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).
- [ ] I have tested Android, Java SE, and Java EE

#### Unit Tests
[Describe the unit tests and behaviors added in this PR]

#### Core Tests
[List of tests performed against Core and behaviors verified]

Core version / branch / commit hash / module tested against: [INSERT]
HMI name / version / branch / commit hash / module tested against: [INSERT]

### Summary
[Summary of PR changes]

### Changelog
##### Breaking Changes
* [Breaking change info]

##### Enhancements
* [Enhancement info]

##### Bug Fixes
* [Bug Fix Info]

### Tasks Remaining:
- [ ] [Task 1]
- [ ] [Task 2]

### CLA
- [ ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2020-11-17 19:23 UTC, RHenigan commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) [SDL 0198] - Media Skip Indicators #871 [0.5]](https://trello.com/c/3Sw6FUMh/515-3-sdl-0198-media-skip-indicators-871-05)

2020-12-21 06:51 UTC, ShobhitAd commented
@RHenigan, the `MAX_SUPPORTED_RPC_VERSION` in sdl_java_suite also needs to be updated to `7.1.0`. Otherwise, the negotiated version will be 7.0 and core will ignore the 7.1 parameters

2021-01-20 21:22 UTC, JulianKast requested changes
very minor formatting issues

2021-01-20 21:22 UTC, JulianKast commented on base/src/main/java/com/smartdevicelink/proxy/rpc/SeekStreamingIndicator.java
> + *      <td>If the type is TIME, this number of seconds may be present alongside the skip indicator.It will indicate the number of seconds that the currently playing media will skip forwardor backwar
```suggestion
 *      <td>If the type is TIME, this number of seconds may be present alongside the skip indicator.It will indicate the number of seconds that the currently playing media will skip forward or backward.</td>
```

2021-01-20 21:22 UTC, JulianKast commented on base/src/main/java/com/smartdevicelink/proxy/rpc/SetMediaClockTimer.java
> + *          <td>Used to control the forward seek button to either skip forward a set amount of time or tothe next track.</td>
```suggestion
 *          <td>Used to control the forward seek button to either skip forward a set amount of time or to the next track.</td>

```

2021-01-20 21:22 UTC, JulianKast commented on base/src/main/java/com/smartdevicelink/proxy/rpc/SetMediaClockTimer.java
> + *          <td>Used to control the forward seek button to either skip back a set amount of time or to theprevious track.</td>
```suggestion
 *          <td>Used to control the forward seek button to either skip back a set amount of time or to the previous track.</td>

```

2021-01-21 14:33 UTC, JulianKast commented on base/src/main/java/com/smartdevicelink/proxy/rpc/SetMediaClockTimer.java
> +
```suggestion

```

2021-01-21 14:33 UTC, JulianKast requested changes

2021-01-21 14:33 UTC, JulianKast commented on base/src/main/java/com/smartdevicelink/proxy/rpc/SetMediaClockTimer.java
> +
```suggestion

```

2021-01-21 14:36 UTC, JulianKast requested changes
One last thing

2021-01-21 15:12 UTC, JulianKast approved these changes

2021-01-21 15:13 UTC, JulianKast commented
Approved, Waiting on cores pr to be merged https://github.com/smartdevicelink/sdl_core/pull/3605

2021-01-28 17:31 UTC, merged