Add Changes from proposal for CustomPlaybackRate
smartdevicelink/sdl_java_suite pull request #1564
Opened 2020-11-18 15:24 UTC by RHenigan

Fixes #1147 

This PR is **[not ready]** for review.

### Risk
This PR makes **[minor]** API changes.

### Testing Plan
- [ ] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [ ] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).
- [ ] I have tested Android, Java SE, and Java EE

#### Unit Tests
[Describe the unit tests and behaviors added in this PR]

#### Core Tests
[List of tests performed against Core and behaviors verified]

Core version / branch / commit hash / module tested against: [INSERT]
HMI name / version / branch / commit hash / module tested against: [INSERT]

### Summary
[Summary of PR changes]

### Changelog
##### Breaking Changes
* [Breaking change info]

##### Enhancements
* [Enhancement info]

##### Bug Fixes
* [Bug Fix Info]

### Tasks Remaining:
- [ ] [Task 1]
- [ ] [Task 2]

### CLA
- [ ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2020-11-18 15:24 UTC, RHenigan commented
![](https://github.trello.services/images/mini-trello-icon.png) [(2) [SDL 0244] Custom Playback Rates for SetMediaClockTimer](https://trello.com/c/G00XL2jR/963-2-sdl-0244-custom-playback-rates-for-setmediaclocktimer)

2021-01-08 21:10 UTC, bilal-alsharifi requested changes

2021-01-08 21:10 UTC, bilal-alsharifi commented on base/src/main/java/com/smartdevicelink/proxy/rpc/SetMediaClockTimer.java
> + *          <td>The value of this parameter is the amount that the media clock timer will advance per 1.0seconds of real time. Values less than 1.0 will therefore advance the timer slower thanreal-ti
```suggestion
 *          <td>The value of this parameter is the amount that the media clock timer will advance per 1.0 seconds of real time. Values less than 1.0 will therefore advance the timer slower than real-time, while values greater than 1.0 will advance the timer faster than real-time.e.g. If this parameter is set to `0.5`, the timer will advance one second per two seconds real-time, or at 50% speed. If this parameter is set to `2.0`, the timer will advance two seconds per one second real-time, or at 200% speed.</td>

```

2021-01-08 22:09 UTC, bilal-alsharifi approved these changes

2021-01-14 20:54 UTC, merged