Add Changes from proposal for Main Menu UI updates
smartdevicelink/sdl_java_suite pull request #1565
Opened 2020-11-18 15:53 UTC by RHenigan

Fixes #1246 

This PR is **[not ready]** for review.

### Risk
This PR makes **[minor]** API changes.

### Testing Plan
- [ ] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [ ] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).
- [ ] I have tested Android, Java SE, and Java EE

#### Unit Tests
[Describe the unit tests and behaviors added in this PR]

#### Core Tests
[List of tests performed against Core and behaviors verified]

Core version / branch / commit hash / module tested against: [INSERT]
HMI name / version / branch / commit hash / module tested against: [INSERT]

### Summary
[Summary of PR changes]

### Changelog
##### Breaking Changes
* [Breaking change info]

##### Enhancements
* [Enhancement info]

##### Bug Fixes
* [Bug Fix Info]

### Tasks Remaining:
- [ ] [Task 1]
- [ ] [Task 2]

### CLA
- [ ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2020-11-18 15:54 UTC, RHenigan commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) [SDL 0267] Main Menu UI Updates [0.25]](https://trello.com/c/t1i7XKoT/1119-3-sdl-0267-main-menu-ui-updates-025)

2021-01-15 16:21 UTC, ShobhitAd commented
@RHenigan I think `MenuParams.java` should also have some changes for the new `secondaryText` and `tertiaryText` parameters(https://github.com/smartdevicelink/rpc_spec/tree/feature/SDL_0267_MainMenuUI#menuparams)

2021-02-08 13:52 UTC, JulianKast requested changes

2021-02-08 15:52 UTC, bilal-alsharifi commented on base/src/main/java/com/smartdevicelink/managers/screen/menu/MenuCell.java
> +    public MenuCell(@NonNull String title, @Nullable SdlArtwork icon, @Nullable String secondaryText, @Nullable String tertiaryText, @Nullable SdlArtwork secondaryArtwork, @Nullable List<String> voic
I suggest reordering the function params in both new constructors so the texts come after each other, and the images come after each other:
```
title, secondaryText, tertiaryText, icon, secondaryArtwork
```

2021-02-09 15:39 UTC, JulianKast approved these changes

2021-02-17 22:59 UTC, JulianKast approved these changes

2021-02-19 14:42 UTC, merged