[0262] Vehicle Data Seat Occupany
smartdevicelink/sdl_java_suite pull request #1578
Opened 2020-12-07 21:13 UTC by kostyaBoss

Fixes #1240

This PR is **[not ready]** for review.

### Risk
This PR makes **[minor]** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).
- [x] I have tested Android, Java SE, and Java EE

#### Unit Tests
Added unit tests to cover new structures and update existing

### Summary
Implement proper changes according to #1240

2020-12-08 10:12 UTC, kostyaBoss commented
@santhanamk This pr is ready for Ford review. I do know that CI has failed, though, it seems the problem is not in pr-related features

2020-12-08 15:51 UTC, joeygrover commented
@kostyaBoss

1. Please avoid removing sections from the PR template and instead filling them out with detailed and helpful information.
2. You removed and therefore did not check that you have signed the CLA.
3. You commented that this is ready for review, but the description in the PR states it is not.
4. You do not provide a Core branch/PR that this was tested against and therefore this PR is not reviewable at this time.
5. Multiple files are completely overwritten, this makes a code review very difficult and is in almost all cases incorrect. It is likely you simply ran the RPC generator and committed the results. This is not an acceptable method for the Java Suite library as there are many corner cases in the RPC classes that the generator does not have information on. The generator is used for new classes, however, modification on existing classes should not come from the generator as it will overwrite the file as seen in this PR. The committed changes should only be the code that actually changed.

2020-12-09 14:01 UTC, vladmu commented
@joeygrover thank you for your feedback, we appreciate your help and will fix all problems you mentioned. However please note that this PR currently is under internal and Ford review, therefore some problems could be present here. We'll do all our best to minimize them before this PR goes to the PMs review.

2020-12-09 14:24 UTC, joeygrover commented
@vladmu I am not performing a content review of the code itself, but as the project maintainer if I see a pull request that is very off it is in the best interest of the SDLC to comment on it right away and ensure that those items can be addressed as to avoid delays. Any pull request in the open will always be visible to the community and will be open to comments, especially those from the project maintainer. We await Ford's approval before performing a thorough review.

2020-12-14 10:29 UTC, santhanamk reviewed
@kostyaBoss Code looks good.  I have suggested a few changes.  Please review, and make the changes as needed.

2020-12-14 10:29 UTC, santhanamk commented on android/sdl_android/src/androidTest/java/com/smartdevicelink/test/TestValues.java
> +    public static final JSONArray JSON_GENERAL_SEATS_OCCUPIED = new JSONArray();
@kostyaBoss I would move lines 435 and 437 (`JSONArray` objects) to below line 563 where the other `JSONArray` declarations are.

2020-12-14 10:29 UTC, santhanamk commented on android/sdl_android/src/androidTest/java/com/smartdevicelink/test/TestValues.java
> +    public static final List<SeatStatus> GENERAL_SEATS_OCCUPIED = new ArrayList<SeatStatus>(1);
@kostyaBoss I would add this declaration `public static final JSONObject JSON_OBJECT_GENERAL_SEATS_OCCUPIED = new JSONObject();` where the other `JSONObjects` are declared (around line 604)

2020-12-14 10:29 UTC, santhanamk commented on android/sdl_android/src/androidTest/java/com/smartdevicelink/test/TestValues.java
> +    public static final JSONArray JSON_GENERAL_SEATS_OCCUPIED = new JSONArray();
@kostyaBoss I would add this declaration `public static final JSONObject JSON_OBJECT_GENERAL_SEATS_BELTED = new JSONObject();` where the other `JSONObjects` are declared (around line 604)

2020-12-14 10:29 UTC, santhanamk commented on android/sdl_android/src/androidTest/java/com/smartdevicelink/test/TestValues.java
> +            JSONArray convertedSeatsOccupied = JsonUtils.createJsonArrayOfJsonObjects(GENERAL_SEATS_OCCUPIED, 1);
@kostyaBoss I would delete lines 1179-1189.

2020-12-14 10:35 UTC, santhanamk reviewed
I would replace lines 1179-1189 with 

`            JSON_OBJECT_GENERAL_SEATS_OCCUPIED.put(SeatStatus.KEY_SEAT_LOCATION, GENERAL_SEAT_LOCATION);
            JSON_OBJECT_GENERAL_SEATS_OCCUPIED.put(SeatStatus.KEY_CONDITION_ACTIVE,GENERAL_BOOLEAN);
            JSON_GENERAL_SEATS_OCCUPIED.put(JSON_OBJECT_GENERAL_SEATS_OCCUPIED);
            JSON_OBJECT_GENERAL_SEATS_BELTED.put(SeatStatus.KEY_SEAT_LOCATION, GENERAL_SEAT_LOCATION);
            JSON_OBJECT_GENERAL_SEATS_BELTED.put(SeatStatus.KEY_CONDITION_ACTIVE,GENERAL_BOOLEAN);
            JSON_GENERAL_SEATS_BELTED.put(JSON_OBJECT_GENERAL_SEATS_BELTED);`

2020-12-21 19:41 UTC, kostyaBoss commented on android/sdl_android/src/androidTest/java/com/smartdevicelink/test/rpc/datatypes/SeatStatusTests.java
> +import com.smartdevicelink.proxy.rpc.Grid;
@santanamk, Grid import is used at the line 67

2020-12-21 21:22 UTC, kostyaBoss commented
@santhanamk I've updated the PR please re-review

2020-12-22 16:14 UTC, santhanamk reviewed
@kostyaBoss I reviewed the changes made from the code review.  It looks good.  I have  a few more suggestions.  Please take a look whenever you get the chance.

2020-12-22 16:14 UTC, santhanamk commented on base/src/main/java/com/smartdevicelink/proxy/rpc/GetVehicleData.java
> -/*
@kostyaBoss It looks like the entire file `GetVehicleData.java` is being regenerated by the code generator tool.  Can you just merge in the changes for this PR (data related to `seatOccupancy`)?

2020-12-22 16:14 UTC, santhanamk commented on base/src/main/java/com/smartdevicelink/proxy/rpc/GetVehicleDataResponse.java
> - * Copyright (c) 2017 - 2019, SmartDeviceLink Consortium, Inc.
@kostyaBoss It looks like the entire file `GetVehicleDataResponse.java` is being regenerated by the code generator tool.  Can you just merge in the changes for this PR (data related to `seatOccupancy`)?

2020-12-22 16:14 UTC, santhanamk commented on base/src/main/java/com/smartdevicelink/proxy/rpc/OnVehicleData.java
> -/*
@kostyaBoss It looks like the entire file `OnVehicleData.java` is being regenerated by the code generator tool.  Can you just merge in the changes for this PR (data related to `seatOccupancy`)?

2020-12-22 16:14 UTC, santhanamk commented on android/sdl_android/src/androidTest/java/com/smartdevicelink/test/Validator.java
>          List<SeatStatus> seatStatuses2 = item2.getSeatsBelted();
@kostyaBoss  On line 3924 I would rename `seatStatuses2` to `seatsBelted2`.

2020-12-22 16:14 UTC, santhanamk commented on android/sdl_android/src/androidTest/java/com/smartdevicelink/test/Validator.java
>          List<SeatStatus> seatStatuses2 = item2.getSeatsBelted();
@kostyaBoss On line 3921 I would rename `seatStatuses1` to `seatsBelted1`.

2020-12-22 16:14 UTC, santhanamk commented on android/sdl_android/src/androidTest/java/com/smartdevicelink/test/VehicleDataHelper.java
> +    public static final List<SeatStatus> SEATS_OCCUPIED = new ArrayList<SeatStatus>(1);
@kostyaBoss Line 97 is in the right place, but you can move the other variables on lines 98-101 back to where they were before.  

Line 97 `SEAT_OCCUPANCY` is the top level variable while the other variables on lines 98-101 are lower variables.

2020-12-29 14:34 UTC, kostyaBoss commented
@santhanamk I've updated the PR, please re-review

2021-01-04 09:30 UTC, santhanamk approved these changes
@kostyaBoss Code looks good. I have approved the PR.

Once you have tested against Core and HMI (if applicable), please put the links for those PRs. Please mark the PR as ready for review, and you can tag Livio once the testing is done on your end.

2021-01-06 21:05 UTC, kostyaBoss commented
@bilal-alsharifi , @jordynmackool the PR is ready for the review

2021-01-12 19:42 UTC, bilal-alsharifi requested changes

2021-01-15 09:22 UTC, kostyaBoss commented on android/sdl_android/src/androidTest/java/com/smartdevicelink/test/TestValues.java
>  import com.smartdevicelink.proxy.rpc.WindowState;
@bilal-alsharifi I've checked the failing test, it's non-related for this PR test `SeatLocationCapabilityTests`, line 91. Previously we were not changing the tests which are not related to the PR. Please, let me know if this has changed

2021-01-15 14:41 UTC, bilal-alsharifi commented on android/sdl_android/src/androidTest/java/com/smartdevicelink/test/TestValues.java
>  import com.smartdevicelink.proxy.rpc.WindowState;
It is passing on develop though so something changed in the PR that made the test fail.

2021-01-18 18:50 UTC, kostyaBoss commented
@bilal-alsharifi I've processed the test, please, re-review

2021-01-19 17:40 UTC, bilal-alsharifi approved these changes

2021-02-03 14:58 UTC, bilal-alsharifi commented
@kostyaBoss It seems that there are merge conflicts now. Can you pull in develop to fix the conflicts?

2021-02-09 14:20 UTC, merged