Override Clone, Equals, and hashcode for RPCStruct
smartdevicelink/sdl_java_suite pull request #1586
Opened 2020-12-10 20:40 UTC by RHenigan

Fixes #116

This PR is **[not ready]** for review.

### Risk
This PR makes **[minor]** API changes.

### Testing Plan
- [X] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [X] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).
- [ ] I have tested Android, Java SE, and Java EE

#### Unit Tests
Added Unit tests to RPCStructTests to verify new method behaviors

### Summary
This PR adds methods to the RPCStruct class to override the Clone, Equals, and hashCode methods.
RPCStruct now implements Clonable and the `clone()` method will create a deepCopy of RPCStruct when called.
`equals()` is now overriden and can be used to compare two RPCStruct objects
`hashCode()` will return the hashCode of the store in the RPCStruct

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2020-12-10 20:53 UTC, RHenigan commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) #116 - RPC classes should implement equals() and hashcode() methods [1.75]](https://trello.com/c/kHBRtlub/1271-3-116-rpc-classes-should-implement-equals-and-hashcode-methods-175)

2020-12-21 20:52 UTC, JulianKast commented on base/src/main/java/com/smartdevicelink/proxy/RPCStruct.java
> +            clone.setBulkData(_bulkData);
```suggestion
            clone.setBulkData(_bulkData);
            clone.store = (Hashtable<String, Object>) store.clone();
```

2021-01-05 13:46 UTC, JulianKast requested changes

2021-01-05 13:46 UTC, JulianKast commented on base/src/main/java/com/smartdevicelink/proxy/RPCStruct.java
> +
Can you add some JavaDocs method headers to added mehtods

2021-01-05 13:46 UTC, JulianKast commented on base/src/main/java/com/smartdevicelink/proxy/RPCStruct.java
> +            clone.setBulkData(_bulkData);
Should we also copy the store?

2021-01-05 13:46 UTC, JulianKast commented on android/sdl_android/src/androidTest/java/com/smartdevicelink/test/proxy/RPCStructTests.java
> +        assertEquals(rpcStruct.hashCode(), 3556536);
It might be better if you created another object here and used that to compare instead of hard coding a number.

2021-01-07 16:58 UTC, merged