Notify ChoiceSetManager of failed preloads
smartdevicelink/sdl_java_suite pull request #1716
Opened 2021-07-07 15:21 UTC by RHenigan

Fixes #1715 

This PR is **not ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
- [X] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [X] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).
- [ ] I have tested Android, Java SE, and Java EE

#### Unit Tests
N/A

#### Core Tests
[List of tests performed against Core and behaviors verified]

Core version / branch / commit hash / module tested against: [INSERT]
HMI name / version / branch / commit hash / module tested against: [INSERT]

### Summary
This PR adds a new ChoiceSetCompletionListener to be used by the PreloadChoicesOperation. In the even that choices fail to preload the new listener is used to notify the BaseChoiceSetManager which choice cells failed to preload.Any choice cells that were successfull will be added to the preloadedChoices and removed from the pendingPreloadChoices.

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-07-09 19:30 UTC, JulianKast reviewed
So if some choices fail to upload while others are successful, when they go to present that choiceSet, should the choices that successfully uploaded be presented?

2021-07-12 12:37 UTC, RHenigan commented
@JulianKast If you try to present a list that requires preloads and some of those preloads failed then the entire present should fail. In the event that a choice set has "Yes" and "No" but yes fails to preload, we do not want to present just "no".

2021-07-15 17:59 UTC, JulianKast approved these changes

2021-07-15 18:09 UTC, JulianKast requested changes

2021-07-15 18:09 UTC, JulianKast commented on base/src/main/java/com/smartdevicelink/managers/ChoiceSetCompletionListener.java
> +public interface ChoiceSetCompletionListener {
Can you make this a part of BaseChoiceSetManager like AlertSoftButtonClearListener in BaseAlertManager?

2021-07-15 19:28 UTC, JulianKast approved these changes

2021-07-20 17:07 UTC, merged