Bugfix/issue 1717 1718
smartdevicelink/sdl_java_suite pull request #1722
Opened 2021-07-26 12:44 UTC by RHenigan

Fixes #1717, #1718

This PR is **not ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).
- [ ] I have tested Android, Java SE, and Java EE

#### Unit Tests
TODO

#### Core Tests
Tested sendin a presentation, then sending another presentation when the first has a button pressed

Core version / branch / commit hash / module tested against: Manticore (SDL v7.1.1)
HMI name / version / branch / commit hash / module tested against: (Generic HMI v0.10.0)

### Summary
[Summary of PR changes]

### Changelog
##### Breaking Changes
* [Breaking change info]

##### Enhancements
* [Enhancement info]

##### Bug Fixes
* [Bug Fix Info]

### Tasks Remaining:
- [ ] [Task 1]
- [ ] [Task 2]

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-08-05 00:39 UTC, JulianKast requested changes
@RHenigan after my first review, I noticed a few small things.

2021-08-05 00:39 UTC, JulianKast commented on base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadChoicesCompletionListener.java
> +public interface PreloadChoicesCompletionListener {
Can you make this internal to BaseChoiceSetManager like what you did on this PR: https://github.com/smartdevicelink/sdl_java_suite/pull/1716/files, also just create one interface to use, as this does the same thing as the `DeleteChoicesCompletingListener` so something like: 

```
    interface ChoiceCompletionListener {
        void onComplete(boolean success, HashSet<ChoiceCell> failedChoiceCells);
    }
```

2021-08-05 00:39 UTC, JulianKast commented on base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java
> +        //Clone Cells
This is my fault from a previous PR as this is just copied from BaseChoiceSetManager.
```suggestion
        // Clone Cells
```

2021-08-05 00:39 UTC, JulianKast commented on base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java
> +    //Choice Uniqueness
```suggestion
    // Choice Uniqueness
```

2021-08-05 00:39 UTC, JulianKast commented on base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java
> +    //Finding Cells
```suggestion
    // Finding Cells
```

2021-08-05 00:39 UTC, JulianKast commented on base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java
> +    //Assembling Choice RPCs
```suggestion
    // Assembling Choice RPCs
```

2021-08-05 00:39 UTC, JulianKast commented on base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java
> +    //SDL Notifications
```suggestion
    // SDL Notifications
```

2021-08-05 00:39 UTC, JulianKast commented on base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java
> +    //Present Helpers
```suggestion
    // Present Helpers
```

2021-08-05 00:39 UTC, JulianKast commented on base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java
> +    //PRELOAD OPERATION METHODS
```suggestion
    // Preload Operation Methods
```

2021-08-09 13:48 UTC, RHenigan commented on base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java
> +    public HashSet<ChoiceCell> getLoadedCells() {
Currently it was not being used and neither was the getter method in DeleteChoicesOperation, I have removed them for now

2021-08-12 15:43 UTC, JulianKast requested changes

2021-08-18 16:17 UTC, JulianKast requested changes

2021-08-18 16:17 UTC, JulianKast commented on base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java
> +                        loadedCells.add(cellFromChoiceId(correlationId));
correlationID does not translate to choiceCell ID so loadedCells are always empty, prompting cells to be uploaded everytime you go to present

2021-09-13 20:06 UTC, JulianKast requested changes

2021-09-13 20:06 UTC, JulianKast commented on base/src/main/java/com/smartdevicelink/managers/screen/choiceset/DeleteChoicesOperation.java
> +                                loadedCells.remove(loadedCellFromChoiceId(correlationId));
I found an issue, Steps to show error:
Step 1: Upload a `ChoiceSet`.
Step 2: Present `ChoiceSet` and select an item.
Step 3: In your `ChoiceSetSelectionListener` retrieve the list of uploaded `ChoiceCell`s and delete one of them.
Step 4: Present `ChoiceSet`

Observed: 
Errors: 

```
2021-09-13 15:58:07.635 28442-28442/com.sdl.hellosdlandroid E/PreloadPresentChoicesOperation: 5.2.0: Presenting Choice set failed: null
2021-09-13 15:58:07.635 28442-28442/com.sdl.hellosdlandroid E/BaseChoiceSetManager: 5.2.0: Present finished but an unhandled state occurred and callback failed
```

Expected: 
The deleted ChoiceCell should be uploaded again and the ChoiceSet should be present.

I traced it back to here, the Correlation ID was 53 and the ChoiceCell ID was 3.

Code I used for testing:
Add this code to `onChoiceSelected` in hello_sdl

```
 HashSet<ChoiceCell> choiceCellHashSet = sdlManager.getScreenManager().getPreloadedChoices();
 List<ChoiceCell> choiceCellList = new ArrayList<>(choiceCellHashSet);
 sdlManager.getScreenManager().deleteChoices(Collections.singletonList(choiceCellList.get(1)));
```

2021-09-16 18:03 UTC, JulianKast requested changes

2021-09-16 19:59 UTC, JulianKast requested changes
minor updates needed

2021-09-16 19:59 UTC, JulianKast commented on android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/choiceset/ChoiceSetManagerTests.java
> +import com.smartdevicelink.managers.CompletionListener;
There are some unused imports in this class related to removed code

2021-09-16 19:59 UTC, JulianKast commented on android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperationTests.java
> +import java.util.List;
```suggestion
```

2021-09-16 19:59 UTC, JulianKast commented on base/src/main/java/com/smartdevicelink/managers/screen/choiceset/BaseChoiceSetManager.java
> -    HashSet<ChoiceCell> preloadedChoices, pendingPreloadChoices;
There are some unused imports in this class related to removed code

2021-09-16 19:59 UTC, JulianKast commented on base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java
> +import com.smartdevicelink.managers.ManagerUtility;
```suggestion
```

2021-09-16 19:59 UTC, JulianKast commented on base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java
> +    //Start choiceId at 1 to ensure all HMIs handle it https://github.com/smartdevicelink/generic_hmi/commit/b292fbbec095b9ce11b520d47ec95b6fcff8e247
```suggestion
    // Start choiceId at 1 to ensure all HMIs handle it https://github.com/smartdevicelink/generic_hmi/commit/b292fbbec095b9ce11b520d47ec95b6fcff8e247
```

2021-09-16 19:59 UTC, JulianKast commented on base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java
> +        //Loop through the cells we need ids for. Get and assign those ids
```suggestion
        // Loop through the cells we need ids for. Get and assign those ids
```

2021-09-16 19:59 UTC, JulianKast commented on base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java
> +            //Insert the ids into the usedIds sorted array in the correct position
```suggestion
            // Insert the ids into the usedIds sorted array in the correct position
```

2021-09-16 19:59 UTC, JulianKast commented on base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java
> +    //Find the next available choice is. Takes into account the loaded cells to ensure there are not duplicates
```suggestion
    // Find the next available choice is. Takes into account the loaded cells to ensure there are not duplicates
```

2021-09-16 19:59 UTC, JulianKast commented on base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java
> +        //Check if we are entirely full, or if we've advanced beyond the max value, loop back
```suggestion
        // Check if we are entirely full, or if we've advanced beyond the max value, loop back
```

2021-09-16 19:59 UTC, JulianKast commented on base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java
> +            //If the last value isn't the max value, just keep grabbing towards the max value
```suggestion
            // If the last value isn't the max value, just keep grabbing towards the max value
```

2021-09-16 19:59 UTC, JulianKast commented on base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java
> +            //All our easy options are gone. Find and grab an empty slot from within the sorted list
```suggestion
            // All our easy options are gone. Find and grab an empty slot from within the sorted list
```

2021-09-16 19:59 UTC, JulianKast commented on base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java
> +                    //This slot is open because the cell id does not match an open sorted slot
```suggestion
                    // This slot is open because the cell id does not match an open sorted slot
```

2021-09-16 19:59 UTC, JulianKast commented on base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java
> +            //This *shouldn't* be possible
```suggestion
            // This *shouldn't* be possible
```

2021-09-16 19:59 UTC, JulianKast commented on base/src/main/java/com/smartdevicelink/managers/screen/choiceset/PreloadPresentChoicesOperation.java
> +            //We haven't looped all the way around yet, so we'll just take the current number, then advance the item
```suggestion
            // We haven't looped all the way around yet, so we'll just take the current number, then advance the item
```

2021-09-16 20:22 UTC, JulianKast approved these changes

2021-09-20 18:06 UTC, merged