check isGraphicSupported in SoftButtonManager
smartdevicelink/sdl_java_suite pull request #1811
Opened 2022-06-02 18:47 UTC by JulianKast

Fixes #1738 

This PR is **[not ready]** for review.

### Risk
This PR makes **[minor]** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [ ] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).
- [x] I have tested Android, Java SE, and Java EE

#### Unit Tests
n/a

#### Core Tests
[List of tests performed against Core and behaviors verified]

Core version / branch / commit hash / module tested against: [INSERT]
HMI name / version / branch / commit hash / module tested against: [INSERT]

### Summary
Checks isGraphicSupported that is received from RegisterAppInterfaceRespomse in `softButtonUpdateOperation` to prevent images form being uploaded on older Sync Systems

### Changelog
##### Breaking Changes
* [Breaking change info]

##### Enhancements
* [Enhancement info]

##### Bug Fixes
* [Bug Fix Info]

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2022-06-08 17:57 UTC, joeljfischer requested changes
A few small items

2022-06-08 17:57 UTC, joeljfischer commented on base/src/main/java/com/smartdevicelink/managers/screen/BaseSoftButtonManager.java
> +    private DisplayCapabilities displayCapabilities;
I don't think you need to store this, just `isGraphicSupported`, right?

2022-06-08 17:57 UTC, joeljfischer commented on android/sdl_android/src/androidTest/java/com/smartdevicelink/managers/screen/SoftButtonManagerTests.java
> +        softButtonManager.isGraphicSupported = true;
You probably should have a test where this is NO and images are not sent

2022-06-15 16:02 UTC, joeygrover requested changes

2022-06-15 16:02 UTC, joeygrover commented on base/src/main/java/com/smartdevicelink/managers/screen/SoftButtonReplaceOperation.java
> +        this.isGraphicSupported = isGraphicSupported;
Can we refactor this to be `isDynamicGraphicSupported`? I just think in the future it will be much clearer what this actually means.

2022-06-15 17:16 UTC, joeygrover approved these changes

2022-06-21 14:14 UTC, merged