Bugfix/issue 1828
smartdevicelink/sdl_java_suite pull request #1831
Opened 2022-09-14 21:09 UTC by ChloeMJM

Fixes #1828

This PR is **ready** for review.

### Risk
This PR makes **minor** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).
- [x] I have tested Android, *Java SE, and *Java EE

#### Unit Tests
*Note: This branch has been tested for Android but needs additional Java SE and Java EE testing.

- `testOnShowFailBadDataDoesNotUpdateScreen()` : Tests the show failure branch within the `sendShow` method which notifies the `currentScreenDataUpdateListener` of an `errorState`.
- `testUpdateTargetStateWithErrorStateNullDoesNotUpdateCurrentScreen()`: Tests the `updateTargetStateWithErrorState` method to ensure that fields set to null will not be updated on the current screen.
- `testUpdateTargetStateWithErrorBadDataDoesNotUpdateCurrentScreen()` : Tests the `updateTargetStateWithErrorState` method to ensure that fields set to bad data will not be updated on the current screen.
- `testUpdateTargetStateWithErrorBadDataAndGoodData()` : Tests the `updateTargetStateWithErrorState` method to ensure that fields set to bad data will not be updated on the current screen but fields set with good data will be updated.

#### Core Tests
In Manticore verified that properties in screen manager when set would not fail when one attribute was given bad data

### Summary
- In `TextAndGraphicUpdateOperation:` modified the `sendShow` method to call `currentScreenDataUpdateListener.onError(updatedState)` on failure.
- Modified the `onError` path of the `currentScreenDataUpdateListener` override to call `updatePendingOperationsWithFailedScreenState(errorState)`, passing in an `errorState`.
- In `BaseTextAndGraphicManager`: added in method `updatePendingOperationsWithFailedScreenState `which sends the `errorState` to `updateOperation.updateTargetStateWithErrorState(errorState)`
- In `TextAndGraphicUpdateOperation`: added method `updateTargetStateWithErrorState` that ensures every field is null safe and compares the `errorState` to the `updatedState`. If they are the same, then it sets the `updatedState` to the `currentScreenData `associated with the field to keep the field from being updated with bad data.
- Added unit tests.

### Changelog

##### Enhancements
* Screen data will update even if other fields may have bad data.

##### Bug Fixes
* Screen data will update even if other fields may have bad data.

### Tasks Remaining
- [x] Create fix.
- [x] Add unit tests.
- [ ] Code review.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2022-09-15 20:36 UTC, JulianKast requested changes
First round code review

2022-09-15 21:40 UTC, ChloeMJM commented on base/src/main/java/com/smartdevicelink/managers/screen/BaseTextAndGraphicManager.java
> +                updatePendingOperationsWithFailedScreenState(errorState);
Okay, I applied this for now, let me know if they say anything different. 
Also applied all other feedback in commit #8.

2022-09-19 20:34 UTC, JulianKast requested changes
Don't stress about code coverage, given the design, it would require a lot of rewriting of current unit tests to get coverage in areas we did not have before to get to 60%

2022-09-20 16:00 UTC, ChloeMJM commented on base/src/main/java/com/smartdevicelink/managers/screen/TextAndGraphicUpdateOperation.java
> +            currentScreenDataUpdateListener.onError(null);
Suggestion applied

2022-09-20 16:01 UTC, ChloeMJM commented on base/src/main/java/com/smartdevicelink/managers/screen/TextAndGraphicUpdateOperation.java
> +                    currentScreenDataUpdateListener.onError(null);
Suggestion applied

2022-09-20 16:01 UTC, ChloeMJM commented on base/src/main/java/com/smartdevicelink/managers/screen/TextAndGraphicUpdateOperation.java
> +            currentScreenDataUpdateListener.onError(null);
Suggestion applied

2022-09-20 18:49 UTC, JulianKast approved these changes

2022-09-21 19:22 UTC, merged