Hot Fix for  #1839. Adding fallback logic for starting router service
smartdevicelink/sdl_java_suite pull request #1840
Opened 2023-02-02 20:35 UTC by joeygrover

Fixes #1839

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).
- [x] I have tested Android, ~Java SE, and Java EE~

#### Unit Tests
None added for this PR as the changes are not unit testable.

#### Core Tests

Tested with a Gen3 Ford TDK
Cycled through testing different permission allocations and who would start and ultimately host the router service.
![image](https://user-images.githubusercontent.com/6579474/216442947-0116585f-f854-40f3-adc5-aec55553571c.png)

### Summary
Essentially added a new logical assumption that all apps need to be targeting Android 12 at this point and therefore require the user granted Nearby Devices permission to receive Bluetooth connection intents. Therefore, if an older version of the library is installed that does not have the newer permission check logic prior to start the RS, if that app does not have the correct permission we can assume they will not be receiving the BT ACL connection intent and we can ignore the old legacy logic that it would have executed. 

We also added a fallback call to start the newest router service in the case there was an older SDL enabled app on the device but their integration was incorrect. 

### Changelog

##### Hot Fix
* Adds better recoverability to the RS starting process when legacy SDL apps are installed on the device.

### Tasks Remaining:
- [ ] Update the versions before officially releasing as a hot fix

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2023-02-06 19:59 UTC, mrapitis commented
>Update the versions before officially releasing as a hot fix

Does this include an increment of the sdl_router_service_version_value value? I noticed the RS version of 17 in the graphic, but still 16 in the sdl.xml file (I can manually adjust to 17 for testing if needed).

2023-02-06 20:04 UTC, joeygrover commented
> > Update the versions before officially releasing as a hot fix
> 
> Does this include an increment of the sdl_router_service_version_value value? I noticed the RS version of 17 in the graphic, but still 16 in the sdl.xml file (I can manually adjust to 17 for testing if needed).

RS version will remain 16. 

So yes, 17 was for testing only and was manually adjusted. Referenced comment is to update the version in the gradle file before merging as a hotfix.

2023-02-08 19:22 UTC, mrapitis approved these changes

2023-02-13 16:43 UTC, JulianKast requested changes
One formatting error, otherwise looks good, Do you want to update the version as well for the release?

2023-02-13 16:43 UTC, JulianKast commented on android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlBroadcastReceiver.java
> +                            } else if(isPreAndroid12RSOnDevice){
```suggestion
                            } else if(isPreAndroid12RSOnDevice) {
```

2023-02-14 18:41 UTC, merged