Android 14 Runtime registered broadcast receivers export behavior
smartdevicelink/sdl_java_suite pull request #1858
Opened 2023-07-26 20:25 UTC by JulianKast

Fixes #1857

This PR is **[not ready]** for review.

### Risk
This PR makes **[no]** API changes.

### Testing Plan
- [ ] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [ ] I have run the unit tests with this PR
- [ ] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).
- [ ] I have tested Android, Java SE, and Java EE

#### Unit Tests
[Describe the unit tests and behaviors added in this PR]

#### Core Tests
[List of tests performed against Core and behaviors verified]

Core version / branch / commit hash / module tested against: [INSERT]
HMI name / version / branch / commit hash / module tested against: [INSERT]

### Summary
This PR updates the gradle files for SDL and Hello SDL to target API level 34, as well as specifies export behavior for runtime-registered broadcasts receivers.

### Changelog
##### Breaking Changes
* [Breaking change info]

##### Enhancements
* [Enhancement info]

##### Bug Fixes
* [Bug Fix Info]

### Tasks Remaining:
- [ ] [Task 1]
- [ ] [Task 2]

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2023-11-03 18:29 UTC, joeygrover requested changes
Couple of places I don't believe the receivers need to be exported. I think it might be helpful to make a method in AndroidTools to handle the version check to make the code more concise (Note: we use the Oreo code because that's when Android added the method signature that includes flags):

```java
    /**
     * A helper method to handle adding flags to registering a run time broadcast receiver.
     *
     * @param context  a context that will be used to register the receiver with
     * @param receiver the receiver that will be registered
     * @param filter   the filter that will be use to filter intents sent to the broadcast receiver
     * @param flags    any flags that should be used to register the receiver. In most cases this
     *                 will be {@link  Context#RECEIVER_NOT_EXPORTED} or
     *                 {@link  Context#RECEIVER_EXPORTED}
     * @see Context#registerReceiver(BroadcastReceiver, IntentFilter)
     * @see Context#registerReceiver(BroadcastReceiver, IntentFilter, int)
     */
    @SuppressLint("UnspecifiedRegisterReceiverFlag")
    public static void registerReceiver(Context context, BroadcastReceiver receiver, IntentFilter filter, int flags) {
        if (context != null && receiver != null && filter != null) {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                context.registerReceiver(receiver, filter, flags);
            } else {
                context.registerReceiver(receiver, filter);
            }
        }
    }
```

I also found two more instances of where we register a receiver that could use the new flag for correctness:

- [TransportManager line 415](https://github.com/smartdevicelink/sdl_java_suite/blob/3e714213b835b2b1f60662e62d397d7db62b2be2/android/sdl_android/src/main/java/com/smartdevicelink/transport/TransportManager.java#L415) - Exported
- [MediaStreamingStatus line 264](https://github.com/smartdevicelink/sdl_java_suite/blob/3e714213b835b2b1f60662e62d397d7db62b2be2/android/sdl_android/src/main/java/com/smartdevicelink/util/MediaStreamingStatus.java#L264) - Exported

2023-11-06 19:53 UTC, JulianKast commented on android/sdl_android/src/main/java/com/smartdevicelink/managers/lockscreen/SDLLockScreenActivity.java
> +            registerReceiver(lockScreenBroadcastReceiver, lockscreenFilter, RECEIVER_EXPORTED);
The lockscreen won't dismiss if it's not exported

2023-11-06 20:09 UTC, JulianKast commented on android/sdl_android/src/main/java/com/smartdevicelink/managers/lockscreen/LockScreenManager.java
> +                        context.get().registerReceiver(mLockscreenDismissedReceiver, new IntentFilter(SDLLockScreenActivity.KEY_LOCKSCREEN_DISMISSED), Context.RECEIVER_EXPORTED);
This receiver does not work unless it is exported.

2023-11-16 16:38 UTC, joeygrover commented on android/sdl_android/src/main/java/com/smartdevicelink/managers/lockscreen/LockScreenManager.java
> +                        context.get().registerReceiver(mLockscreenDismissedReceiver, new IntentFilter(SDLLockScreenActivity.KEY_LOCKSCREEN_DISMISSED), Context.RECEIVER_EXPORTED);
The issue is that the original intent does not have a package attached to it. So do a find usage on the intents received by this receiver, and where they are created the following line needs to get added before they are sent via broadcast and then setting these to not exported works correctly:

```java
intent.setPackage(context.get().getPackageName())
```

2023-11-16 16:39 UTC, joeygrover commented on android/sdl_android/src/main/java/com/smartdevicelink/managers/lockscreen/SDLLockScreenActivity.java
> +            registerReceiver(lockScreenBroadcastReceiver, lockscreenFilter, RECEIVER_EXPORTED);
Same comment as above.

2023-11-17 18:48 UTC, joeygrover approved these changes

2023-11-17 18:48 UTC, merged